home:
    path: /
    defaults:
        _controller: AppBundle:Front\Default:index
    
login:
    path: /login
    defaults:
        _controller: AppBundle:Front/Security:login

register:
    path: /register
    defaults:
        _controller: AppBundle:Front/Registration:register

logout:
    path: /logout
    defaults:
        _controller: AppBundle:Front/Security:logout
        
login_check_route:
    path: /login_check
    defaults:
        _controller: AppBundle:Front/Security:loginCheck