<?php

namespace AppBundle\Repository;

/**
 * PointsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointsRepository extends \Doctrine\ORM\EntityRepository
{

	public function getPointsJson()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT u FROM AppBundle:Points u");
        return $points = $query->getResult();    
    }

    public function getUserPoints($id)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT u FROM AppBundle:Points u WHERE u.userId = $id");
        return $points = $query->getResult();
    }
}
